meta:
  bosh-network:
    cidr:
  openstack: null
  floating_static_ips:
  stemcell:
    name: bosh-openstack-kvm-ubuntu-lucid-go_agent
    version: latest
  environment: cf
director_uuid: DELETE_ME
jobs:
  ha_proxy_z1:
    properties:
      ha_proxy:
        ssl_pem: '-----BEGIN PRIVATE KEY-----

          MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC0qVqvF3LSEuPx

          pm8Qr3nemnGlkZRbyiBcN3gzOQzfbZWU9BesKOgrGVldkKNVfKfcEMa8PiGFodp3

          O451aX/rOvyAjYpq++gfRFbVJSuCvm8qTifc5R3mLe/OLdlr7J9J8PoCf4tw4Qs+

          ND/9eaiCBgjzoMX1bJlKcYOo7VVnmRe7dhY1z8Kn7k4jHf/noFYXwI981NGDxyMz

          MjuepjEt6zLDl2YKTmEGN1ibpMOxeJbmbkSwevkxDCUl2Ys++WemCqjLPsafxlr1

          x+HzT9jyxWZsJAcNmcB6VMKLdYQPuB+fI6ckhCgzFp1skC2B5YAc7uUSVTs2HoIX

          gl0FMyZJAgMBAAECggEBAJ9MMRzwZRsc8wbxxT8GK0SAFDN0sUdaa7xEYOVxqYsc

          +mcz7+eqzkSqfmUFEzBe0Tg3RrVXZ4GIXLUDu7KFyvhks566r1F0O5HOVW5t7vbC

          6gx4i6e4EuwSlz/Kp8sFAtNU+23WfuKSXLKFqeLcMhwsLBp+Ke8kyemdPAVo+AR2

          urVh1Avip777hQHohpsTRuEhmT5UWN+Cn2CVKDMLUaYeTsA7eiZbQiQm6BXwDvgW

          zNrSO3fIcJytc5T8o6gVYgYGbQE0V6/uv/BdDqAY8+JMq3I2f7hZ4FlZmKsgbaHU

          zYJrlYC0GKAD/X5jFYqd7kvJxvHtaO87w407W0cIsm0CgYEA3ydPAfXCK4PkkWKt

          dfUX8P9+c9p0xjhKwIPJsKZ34SgbCGaeIhugU9jZW9wxmbHEB1te0eUHp6LM3/mA

          +CyZJGtOmuR0UrASZGK/svWWItdUAD0Jxa2TJjVnB1Cm148y0rJN2+USJU3WgCcd

          xDeS0wt8BTGVZt+t9wwvo2v2ulMCgYEAz0DlZ+0uZYn6HfDiaCperDsbf5BCDl61

          zLIXMvKZ5ePIFw34rKoHo28qqNfZmc3ZtQBFQlRsiM6O3lBo/5HVSoT+ZPQx1VI4

          oFshCCXMFluooByseo34xNPuaLm4JMOHJFKX3vFPSFhYXLwTtc2h4IiPOmTulJu9

          jCSVcaOsYXMCgYANSGy2hCdrqa0oTkRe+hjTupGPWdiLl/wzG2UdA7utBlMdm+Yb

          x6Myenztr9yv9lnhyjmJquVawCELz/EyVI1FErIaHDEkXuCpYwtgHqgyKLkSTo/P

          WXah1pnsYIud1yNCUWS7Cxaaa9ixxiJKdLhjoZJfSMVI21Wil/IZ+yoziwKBgA3R

          0/o0FI3sv2LTtyUe/iUZ4+GDqwPuSM0XaviYuK5dm+/9nIFW7R92wC92BSp+UXAC

          Tpv3qS0OKPSmA/pWrRRE/fmZVuFUlDYNHYy/iHZNMldK0i1x3g6x2wncqGy7JP3F

          DB9vk8vNKEc2u1G6HnssX/CS3l3GbMM1hUmIkmwFAoGBAIqOFo0hDPznEhyc9BqP

          P1g61aPwrTrnByHlDbqa7By5d3UXahYxG69HnPKKQL4GRhpI01D1etKU7LfMEKBt

          sFbUXHkSRvJ6YyVk5VNdLJaqeUsiomPoyPDQQ9Va57LoPYdtWftVLrAwmdh8nlqC

          nJSe2omvx1waiPI9xgq7KjHq

          -----END PRIVATE KEY-----

          -----BEGIN CERTIFICATE-----

          MIIEBTCCAu2gAwIBAgIBADANBgkqhkiG9w0BAQUFADCBnDELMAkGA1UEBhMCVVMx

          EzARBgNVBAgMCkNBTElGT1JOSUExFjAUBgNVBAcMDVNhbiBGcmFuY2lzY28xDDAK

          BgNVBAoMA1dNRzELMAkGA1UECwwCSVQxHjAcBgNVBAMMFSouMTAuMjQxLjEuMTQ0

          LnhpcC5pbzElMCMGCSqGSIb3DQEJARYWaW5mcmFzdHJ1Y3R1cmVAd21nLmNvbTAe

          Fw0xNDA2MjQxNzUzMjVaFw0xNTA2MjQxNzUzMjVaMIGcMQswCQYDVQQGEwJVUzET

          MBEGA1UECAwKQ0FMSUZPUk5JQTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNjbzEMMAoG

          A1UECgwDV01HMQswCQYDVQQLDAJJVDEeMBwGA1UEAwwVKi4xMC4yNDEuMS4xNDQu

          eGlwLmlvMSUwIwYJKoZIhvcNAQkBFhZpbmZyYXN0cnVjdHVyZUB3bWcuY29tMIIB

          IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtKlarxdy0hLj8aZvEK953ppx

          pZGUW8ogXDd4MzkM322VlPQXrCjoKxlZXZCjVXyn3BDGvD4hhaHadzuOdWl/6zr8

          gI2KavvoH0RW1SUrgr5vKk4n3OUd5i3vzi3Za+yfSfD6An+LcOELPjQ//XmoggYI

          86DF9WyZSnGDqO1VZ5kXu3YWNc/Cp+5OIx3/56BWF8CPfNTRg8cjMzI7nqYxLesy

          w5dmCk5hBjdYm6TDsXiW5m5EsHr5MQwlJdmLPvlnpgqoyz7Gn8Za9cfh80/Y8sVm

          bCQHDZnAelTCi3WED7gfnyOnJIQoMxadbJAtgeWAHO7lElU7Nh6CF4JdBTMmSQID

          AQABo1AwTjAdBgNVHQ4EFgQUrxXnkZVYtbJSb1Xlsr051C6+KXowHwYDVR0jBBgw

          FoAUrxXnkZVYtbJSb1Xlsr051C6+KXowDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0B

          AQUFAAOCAQEAAKEcm18EsYuTWZwEzR7eLY/oWHaSFjmgZRUWozyepEdwoG1uVUyl

          0JKjy/0NfQbavcf6/PC/gbzx7D7/h11r6RwoagJsjie43t7bbIPvWpsT9GMn0C3l

          C8516VwEl3XZ9NNcMWJ2MWByZyIHc2NrnaKLyhSQwovFn4Xam+uQ+RemIxZ7M3/X

          2yO5psb7UbhPPMXqGKiIGAKtCDUL6lYSiMILojVVmusjFechgPpHsj4FuVtthiSF

          UWeNgWURGJ/dsZlPS6kvIldJysHAlcslwVuViIjqRc8TstxjUJYQ4LsLCbxwVUYl

          HsC3XHyf7oHqw27el8ueOO/xGlz77FZdZw==

          -----END CERTIFICATE-----'
    instances: 1
    networks:
      cf1:
        default: [ 'dns', 'gateway']
  etcd_z1:
    instances: 1
  login_z2:
    instances: 0

networks:
  floating:
    type: vip
    cloud_properties:
      net_id:
  cf1: {}
  cf-dynamic:
    cloud_properties:
      net_id:
      security_groups:
      - cf-public
      - cf-private
      - ssh
    range:
    type: dynamic
  cf2:
    type: manual
    subnets:
      - name: default_unused
        range: 10.0.0.0/23
        gateway: 10.0.0.1
        reserved: []
        static:
        - 10.0.0.2 - 10.0.0.250
        cloud_properties:
          net_id: MICROBOSH_SUBNET_ID
          security_groups:
          - cf-public
          - cf-private
          - ssh
properties:
  login:
    protocol: http
  ssl:
    skip_cert_verify: true
  domain: ((  meta.floating_static_ips.[0] "xip.io" ))
  loggregator_endpoint:
    shared_secret: 1p@ss4cf
  cc:
    bulk_api_password: 1p@ss4cf
    db_encryption_key: 1p@ss4cf
    staging_upload_password: upload-password
    staging_upload_user: upload-user
  databases:
    roles:
    - name: ccadmin
      password: ccadmin
      tag: admin
    - name: uaaadmin
      password: uaaadmin
      tag: admin
  ccdb:
    roles:
    - name: ccadmin
      password: ccadmin
  uaadb:
    roles:
    - name: uaaadmin
      password: uaaadmin
  uaa:
    admin:
      client_secret: 1p@ss4cf
    batch:
      password: 1p@ss4cf
      username: batch
    cc:
      client_secret: 1p@ss4cf
    clients:
      app-direct:
        secret: 1p@ss4cf
      developer_console:
        secret: 1p@ss4cf
      login:
        secret: 1p@ss4cf
      servicesmgmt:
        secret: 1p@ss4cf
      space-mail:
        secret: 1p@ss4cf
      support-services:
        secret: 1p@ss4cf
    jwt:
      signing_key: '-----BEGIN RSA PRIVATE KEY-----

        MIICXAIBAAKBgQDHFr+KICms+tuT1OXJwhCUmR2dKVy7psa8xzElSyzqx7oJyfJ1

        JZyOzToj9T5SfTIq396agbHJWVfYphNahvZ/7uMXqHxf+ZH9BL1gk9Y6kCnbM5R6

        0gfwjyW1/dQPjOzn9N394zd2FJoFHwdq9Qs0wBugspULZVNRxq7veq/fzwIDAQAB

        AoGBAJ8dRTQFhIllbHx4GLbpTQsWXJ6w4hZvskJKCLM/o8R4n+0W45pQ1xEiYKdA

        Z/DRcnjltylRImBD8XuLL8iYOQSZXNMb1h3g5/UGbUXLmCgQLOUUlnYt34QOQm+0

        KvUqfMSFBbKMsYBAoQmNdTHBaz3dZa8ON9hh/f5TT8u0OWNRAkEA5opzsIXv+52J

        duc1VGyX3SwlxiE2dStW8wZqGiuLH142n6MKnkLU4ctNLiclw6BZePXFZYIK+AkE

        xQ+k16je5QJBAN0TIKMPWIbbHVr5rkdUqOyezlFFWYOwnMmw/BKa1d3zp54VP/P8

        +5aQ2d4sMoKEOfdWH7UqMe3FszfYFvSu5KMCQFMYeFaaEEP7Jn8rGzfQ5HQd44ek

        lQJqmq6CE2BXbY/i34FuvPcKU70HEEygY6Y9d8J3o6zQ0K9SYNu+pcXt4lkCQA3h

        jJQQe5uEGJTExqed7jllQ0khFJzLMx0K6tj0NeeIzAaGCQz13oo2sCdeGRHO4aDh

        HH6Qlq/6UOV5wP8+GAcCQFgRCcB+hrje8hfEEefHcFpyKH+5g1Eu1k0mLrxK2zd+

        4SlotYRHgPCEubokb2S1zfZDWIXW3HmggnGgM949TlY=

        -----END RSA PRIVATE KEY-----

'
      verification_key: '-----BEGIN PUBLIC KEY-----

        MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDHFr+KICms+tuT1OXJwhCUmR2d

        KVy7psa8xzElSyzqx7oJyfJ1JZyOzToj9T5SfTIq396agbHJWVfYphNahvZ/7uMX

        qHxf+ZH9BL1gk9Y6kCnbM5R60gfwjyW1/dQPjOzn9N394zd2FJoFHwdq9Qs0wBug

        spULZVNRxq7veq/fzwIDAQAB

        -----END PUBLIC KEY-----

'
    scim:
      userids_enabled: false
      users:
      - admin|admin|scim.write,scim.read,openid,cloud_controller.admin,uaa.admin,password.write
      - services|1p@ss4cf|scim.write,scim.read,openid,cloud_controller.admin
  nats:
    password: nats
    user: nats
  dea_next:
    disk_mb: 10000
    memory_mb: 1024
  router:
    status:
      password: router
      user: router

