#!/usr/bin/env ruby

require 'tmpdir'

if ARGV.empty?
  puts 'Usage: ./generate_manifest STUB_PATH.' 
  exit 1
end

xml = ''
Dir.chdir(File.dirname(File.expand_path(__FILE__))) do
  xml = `spiff m bosh-deployment.yml bosh-properties.yml bosh-jobs.yml bosh-infrastructure-openstack.yml bosh-networks.yml #{ARGV[0]}`
end
File.open('deployment.yml','w'){ |file| f.write(xml) }

